version: "3"
services:
    init:
        build:
            context: .
        volumes:
            - .:/web
            - .code:/var/www/html
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "20080:80"
        volumes:
            - ./code:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mysql
        volumes:
            - .:/web
            - ./code:/var/www/html
        ports:
            - "9000:9000"
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - .:/web
    mysql:
        image: mysql:latest
        environment: 
            - MYSQL_ROOT_PASSWORD=123456

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "20082:80"
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=123456
            - PHP_UPLOAD_MAX_FILESIZE=100MB
    maildev:
        image: djfarrelly/maildev
        ports:
            - "20081:80"
