version: "3"
services:
    web:
      image: nginx:alpine
      ports:
        - "20080:80"
      volumes:
        - ./code:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php

    php:
      build: .
      links:
        - mysql
        - maildev
    
    mysql:
      image: mysql:latest
      environment: 
        - MYSQL_ROOT_PASSWORD=123456

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - "20082:80"
      environment:
        - PMA_USER=root
        - PMA_PASSWORD=123456
        - PHP_UPLOAD_MAX_FILESIZE=100MB

    maildev:
      image: djfarrelly/maildev
      ports:
       - "20081:80"
